name : In the Cave
brand : In the Cave
description : Philosophy!
keyword: 
url : http://inthecave.github.io/foundation/
email : schultzbergin@gmail.com
twitter : immarcussb
github : inthecave
author: Marcus Schultz-Bergin
analytics: UA-56072237-1
year: 2014
markdown: kramdown
permalink: /:categories/:title/